# Site
name: "Mediumish"
title: "Mediumish"
description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
permalink: /blogs/:title/

# Authors
authors:
  gc:
    name: name
    display_name: display name
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: address@domain.com
    web: https://website.com
    twitter: https://twitter.com/handle
    description: "Description about the author"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [Gemfile, Gemfile.lock]
